# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLIo774dArAGkaAd1SEGQg52T3y4uOBs
"""

"""
AI Medical Prescription Verification System
Complete implementation with Drug Interaction Detection, Dosage Recommendations,
Alternative Suggestions, and NLP-based Information Extraction
"""

# Install required packages
import subprocess
import sys

packages = [
    'transformers',
    'torch',
    'gradio',
    'accelerate',
    'bitsandbytes',
    'sentencepiece',
    'protobuf'
]

print("Installing required packages...")
for package in packages:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', package])

import gradio as gr
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import re
import json
from typing import List, Dict, Tuple
import warnings
warnings.filterwarnings('ignore')

# ==================== DRUG DATABASE ====================

DRUG_DATABASE = {
    # Cardiovascular drugs
    "warfarin": {
        "category": "anticoagulant",
        "interactions": ["aspirin", "ibuprofen", "naproxen", "amiodarone", "ciprofloxacin"],
        "contraindications": ["pregnancy", "bleeding disorders"],
        "dosage": {"adult": "2-10mg daily", "elderly": "1-5mg daily", "child": "not recommended"},
        "alternatives": ["apixaban", "rivaroxaban", "dabigatran"]
    },
    "aspirin": {
        "category": "antiplatelet",
        "interactions": ["warfarin", "ibuprofen", "naproxen", "clopidogrel"],
        "contraindications": ["peptic ulcer", "hemophilia", "children under 12"],
        "dosage": {"adult": "75-325mg daily", "elderly": "75-150mg daily", "child": "not recommended"},
        "alternatives": ["clopidogrel", "ticagrelor"]
    },
    "metoprolol": {
        "category": "beta-blocker",
        "interactions": ["verapamil", "diltiazem", "insulin", "epinephrine"],
        "contraindications": ["asthma", "severe bradycardia", "heart block"],
        "dosage": {"adult": "50-200mg daily", "elderly": "25-100mg daily", "child": "consult pediatrician"},
        "alternatives": ["atenolol", "carvedilol", "bisoprolol"]
    },
    "lisinopril": {
        "category": "ace-inhibitor",
        "interactions": ["potassium supplements", "spironolactone", "nsaids"],
        "contraindications": ["pregnancy", "angioedema history"],
        "dosage": {"adult": "10-40mg daily", "elderly": "5-20mg daily", "child": "not recommended"},
        "alternatives": ["losartan", "valsartan", "enalapril"]
    },
    "amiodarone": {
        "category": "antiarrhythmic",
        "interactions": ["warfarin", "digoxin", "simvastatin", "diltiazem"],
        "contraindications": ["thyroid disorders", "pregnancy"],
        "dosage": {"adult": "200-400mg daily", "elderly": "100-200mg daily", "child": "specialist only"},
        "alternatives": ["sotalol", "dronedarone"]
    },

    # Antibiotics
    "ciprofloxacin": {
        "category": "antibiotic",
        "interactions": ["warfarin", "theophylline", "antacids", "iron supplements"],
        "contraindications": ["pregnancy", "children", "tendon disorders"],
        "dosage": {"adult": "250-750mg twice daily", "elderly": "250-500mg twice daily", "child": "not recommended"},
        "alternatives": ["levofloxacin", "azithromycin", "amoxicillin"]
    },
    "amoxicillin": {
        "category": "antibiotic",
        "interactions": ["methotrexate", "allopurinol", "oral contraceptives"],
        "contraindications": ["penicillin allergy", "mononucleosis"],
        "dosage": {"adult": "250-500mg three times daily", "elderly": "250-500mg three times daily", "child": "20-40mg/kg/day"},
        "alternatives": ["cephalexin", "azithromycin", "clarithromycin"]
    },
    "azithromycin": {
        "category": "antibiotic",
        "interactions": ["warfarin", "digoxin", "ergotamine"],
        "contraindications": ["liver disease", "qt prolongation"],
        "dosage": {"adult": "500mg day 1, then 250mg daily", "elderly": "same as adult", "child": "10mg/kg day 1, then 5mg/kg"},
        "alternatives": ["clarithromycin", "erythromycin", "doxycycline"]
    },

    # Pain medications
    "ibuprofen": {
        "category": "nsaid",
        "interactions": ["warfarin", "aspirin", "lisinopril", "methotrexate"],
        "contraindications": ["peptic ulcer", "severe heart failure", "third trimester pregnancy"],
        "dosage": {"adult": "200-800mg three times daily", "elderly": "200-400mg three times daily", "child": "10mg/kg every 6-8 hours"},
        "alternatives": ["naproxen", "acetaminophen", "celecoxib"]
    },
    "naproxen": {
        "category": "nsaid",
        "interactions": ["warfarin", "aspirin", "lisinopril", "methotrexate"],
        "contraindications": ["peptic ulcer", "severe heart failure", "pregnancy"],
        "dosage": {"adult": "250-500mg twice daily", "elderly": "220-440mg twice daily", "child": "5-7mg/kg twice daily"},
        "alternatives": ["ibuprofen", "acetaminophen", "diclofenac"]
    },
    "acetaminophen": {
        "category": "analgesic",
        "interactions": ["warfarin (high doses)", "alcohol", "isoniazid"],
        "contraindications": ["severe liver disease"],
        "dosage": {"adult": "325-1000mg every 4-6 hours", "elderly": "325-650mg every 4-6 hours", "child": "10-15mg/kg every 4-6 hours"},
        "alternatives": ["ibuprofen", "naproxen"]
    },

    # Diabetes medications
    "metformin": {
        "category": "antidiabetic",
        "interactions": ["contrast dye", "alcohol", "cimetidine"],
        "contraindications": ["kidney disease", "liver disease", "heart failure"],
        "dosage": {"adult": "500-2000mg daily", "elderly": "500-1000mg daily", "child": "500-2000mg daily (>10 years)"},
        "alternatives": ["glipizide", "sitagliptin", "empagliflozin"]
    },
    "insulin": {
        "category": "antidiabetic",
        "interactions": ["metoprolol", "alcohol", "corticosteroids"],
        "contraindications": ["hypoglycemia"],
        "dosage": {"adult": "individualized", "elderly": "individualized", "child": "individualized"},
        "alternatives": ["metformin", "glipizide", "liraglutide"]
    },

    # Cholesterol medications
    "simvastatin": {
        "category": "statin",
        "interactions": ["amiodarone", "amlodipine", "grapefruit juice", "gemfibrozil"],
        "contraindications": ["pregnancy", "active liver disease"],
        "dosage": {"adult": "10-40mg daily", "elderly": "10-20mg daily", "child": "not recommended"},
        "alternatives": ["atorvastatin", "rosuvastatin", "pravastatin"]
    },
    "atorvastatin": {
        "category": "statin",
        "interactions": ["cyclosporine", "clarithromycin", "grapefruit juice"],
        "contraindications": ["pregnancy", "active liver disease"],
        "dosage": {"adult": "10-80mg daily", "elderly": "10-40mg daily", "child": "specialist only"},
        "alternatives": ["simvastatin", "rosuvastatin", "pravastatin"]
    },

    # Additional common medications
    "omeprazole": {
        "category": "proton pump inhibitor",
        "interactions": ["clopidogrel", "methotrexate", "digoxin"],
        "contraindications": ["hypersensitivity"],
        "dosage": {"adult": "20-40mg daily", "elderly": "20mg daily", "child": "0.7-3.3mg/kg daily"},
        "alternatives": ["pantoprazole", "esomeprazole", "lansoprazole"]
    },
    "levothyroxine": {
        "category": "thyroid hormone",
        "interactions": ["iron", "calcium", "antacids", "warfarin"],
        "contraindications": ["untreated adrenal insufficiency"],
        "dosage": {"adult": "50-200mcg daily", "elderly": "25-100mcg daily", "child": "individualized"},
        "alternatives": ["liothyronine", "armour thyroid"]
    },
    "prednisone": {
        "category": "corticosteroid",
        "interactions": ["nsaids", "warfarin", "insulin", "vaccines"],
        "contraindications": ["systemic fungal infection"],
        "dosage": {"adult": "5-60mg daily", "elderly": "5-40mg daily", "child": "0.05-2mg/kg daily"},
        "alternatives": ["methylprednisolone", "dexamethasone", "hydrocortisone"]
    },
    "sertraline": {
        "category": "ssri antidepressant",
        "interactions": ["maoi", "warfarin", "nsaids", "tramadol"],
        "contraindications": ["moai use within 14 days"],
        "dosage": {"adult": "50-200mg daily", "elderly": "25-100mg daily", "child": "25-200mg daily (>6 years)"},
        "alternatives": ["fluoxetine", "escitalopram", "citalopram"]
    },
    "gabapentin": {
        "category": "anticonvulsant",
        "interactions": ["antacids", "morphine", "hydrocodone"],
        "contraindications": ["hypersensitivity"],
        "dosage": {"adult": "300-3600mg daily", "elderly": "300-1800mg daily", "child": "10-15mg/kg three times daily"},
        "alternatives": ["pregabalin", "carbamazepine", "duloxetine"]
    }
}

# ==================== AI MODEL INITIALIZATION ====================

print("Loading IBM Granite 2B model... This may take a few minutes.")

# Using IBM Granite 3.0 2B Instruct - lightweight and optimized for medical tasks
model_name = "ibm-granite/granite-3.0-2b-instruct"

try:
    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True,
        low_cpu_mem_usage=True
    )
    print("✓ IBM Granite 2B Model loaded successfully!")
except Exception as e:
    print(f"Error loading model: {e}")
    print("Falling back to CPU mode...")
    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        trust_remote_code=True,
        low_cpu_mem_usage=True
    )

# ==================== CORE FUNCTIONS ====================

def extract_drugs_from_text(text: str) -> List[str]:
    """Extract drug names from unstructured text using NLP"""
    text_lower = text.lower()
    found_drugs = []

    # Direct database matching
    for drug_name in DRUG_DATABASE.keys():
        if drug_name in text_lower:
            found_drugs.append(drug_name)

    # Use AI model for extraction if no drugs found
    if not found_drugs:
        # IBM Granite prompt format
        prompt = f"""<|system|>
You are an expert medical AI assistant specialized in analyzing prescriptions and extracting medication information.
<|end|>
<|user|>
Extract all medication names from this text: "{text}"
List only the drug names, one per line, in lowercase.
<|end|>
<|assistant|>
"""

        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=100,
                temperature=0.3,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id
            )

        response = tokenizer.decode(outputs[0], skip_special_tokens=True)
        response = response.split("<|assistant|>")[-1].strip()

        # Extract drug names from response
        for line in response.split('\n'):
            drug = line.strip().lower().replace('-', '').replace('.', '')
            if drug in DRUG_DATABASE:
                found_drugs.append(drug)

    return list(set(found_drugs))

def extract_structured_info(text: str) -> Dict:
    """Extract structured drug information using IBM Granite NLP"""

    # IBM Granite prompt format
    prompt = f"""<|system|>
You are an expert medical AI assistant specialized in analyzing prescriptions and extracting structured information.
<|end|>
<|user|>
Analyze this prescription text and extract:
1. Drug name
2. Dosage (amount and unit)
3. Frequency (how often)
4. Duration (if mentioned)

Text: "{text}"

Format your response as:
Drug: [name]
Dosage: [amount]
Frequency: [times per day]
Duration: [days/weeks]
<|end|>
<|assistant|>
"""

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=150,
            temperature=0.3,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    response = response.split("<|assistant|>")[-1].strip()

    # Parse the response
    info = {
        "drug": "",
        "dosage": "",
        "frequency": "",
        "duration": ""
    }

    for line in response.split('\n'):
        if ':' in line:
            key, value = line.split(':', 1)
            key = key.strip().lower()
            value = value.strip()
            if key == "drug":
                info["drug"] = value
            elif key == "dosage":
                info["dosage"] = value
            elif key == "frequency":
                info["frequency"] = value
            elif key == "duration":
                info["duration"] = value

    return info

def check_drug_interactions(drugs: List[str]) -> List[Dict]:
    """Detect harmful drug interactions"""
    interactions = []

    for i, drug1 in enumerate(drugs):
        if drug1 not in DRUG_DATABASE:
            continue

        for drug2 in drugs[i+1:]:
            if drug2 not in DRUG_DATABASE:
                continue

            if drug2 in DRUG_DATABASE[drug1]["interactions"]:
                interactions.append({
                    "drug1": drug1,
                    "drug2": drug2,
                    "severity": "HIGH",
                    "description": f"{drug1.title()} and {drug2.title()} may interact, potentially causing adverse effects."
                })

    return interactions

def get_age_appropriate_dosage(drug: str, age: int) -> Dict:
    """Recommend dosage based on patient age"""
    if drug not in DRUG_DATABASE:
        return {"status": "error", "message": f"Drug '{drug}' not found in database"}

    drug_info = DRUG_DATABASE[drug]

    if age < 12:
        age_group = "child"
        category = "Pediatric"
    elif age >= 65:
        age_group = "elderly"
        category = "Geriatric"
    else:
        age_group = "adult"
        category = "Adult"

    dosage = drug_info["dosage"].get(age_group, "Consult healthcare provider")

    return {
        "status": "success",
        "drug": drug,
        "age": age,
        "category": category,
        "recommended_dosage": dosage,
        "warnings": drug_info["contraindications"]
    }

def suggest_alternatives(drug: str, reason: str = "") -> List[str]:
    """Suggest alternative medications"""
    if drug not in DRUG_DATABASE:
        return []

    return DRUG_DATABASE[drug]["alternatives"]

def analyze_prescription(prescription_text: str, patient_age: int, additional_drugs: str = "") -> str:
    """Main analysis function"""

    results = []
    results.append("=" * 60)
    results.append("AI MEDICAL PRESCRIPTION VERIFICATION REPORT")
    results.append("=" * 60)
    results.append("")

    # 1. NLP-based Drug Extraction
    results.append("📋 STEP 1: DRUG INFORMATION EXTRACTION")
    results.append("-" * 60)

    structured_info = extract_structured_info(prescription_text)
    results.append(f"Drug Name: {structured_info['drug']}")
    results.append(f"Dosage: {structured_info['dosage']}")
    results.append(f"Frequency: {structured_info['frequency']}")
    results.append(f"Duration: {structured_info['duration']}")
    results.append("")

    # Extract all drugs
    all_drugs = extract_drugs_from_text(prescription_text)
    if additional_drugs:
        all_drugs.extend(extract_drugs_from_text(additional_drugs))
    all_drugs = list(set(all_drugs))

    results.append(f"Detected Medications: {', '.join([d.title() for d in all_drugs]) if all_drugs else 'None'}")
    results.append("")

    # 2. Drug Interaction Detection
    results.append("⚠️  STEP 2: DRUG INTERACTION ANALYSIS")
    results.append("-" * 60)

    interactions = check_drug_interactions(all_drugs)
    if interactions:
        results.append(f"⚠️  WARNING: {len(interactions)} potential interaction(s) detected!")
        results.append("")
        for idx, interaction in enumerate(interactions, 1):
            results.append(f"{idx}. {interaction['drug1'].title()} ↔ {interaction['drug2'].title()}")
            results.append(f"   Severity: {interaction['severity']}")
            results.append(f"   Details: {interaction['description']}")
            results.append("")
    else:
        results.append("✓ No significant drug interactions detected.")
        results.append("")

    # 3. Age-Appropriate Dosage
    results.append("💊 STEP 3: AGE-APPROPRIATE DOSAGE RECOMMENDATIONS")
    results.append("-" * 60)
    results.append(f"Patient Age: {patient_age} years")
    results.append("")

    for drug in all_drugs:
        dosage_info = get_age_appropriate_dosage(drug, patient_age)
        if dosage_info["status"] == "success":
            results.append(f"Drug: {drug.title()}")
            results.append(f"Category: {dosage_info['category']} Patient")
            results.append(f"Recommended Dosage: {dosage_info['recommended_dosage']}")
            if dosage_info['warnings']:
                results.append(f"⚠️  Contraindications: {', '.join(dosage_info['warnings'])}")
            results.append("")

    # 4. Alternative Medication Suggestions
    if interactions:
        results.append("🔄 STEP 4: ALTERNATIVE MEDICATION SUGGESTIONS")
        results.append("-" * 60)
        results.append("Based on detected interactions, consider these alternatives:")
        results.append("")

        for interaction in interactions:
            drug1 = interaction['drug1']
            alternatives = suggest_alternatives(drug1)
            if alternatives:
                results.append(f"Instead of {drug1.title()}, consider:")
                for alt in alternatives:
                    results.append(f"  • {alt.title()}")
                results.append("")

    # Safety Summary
    results.append("=" * 60)
    results.append("📊 SAFETY SUMMARY")
    results.append("=" * 60)

    if interactions:
        results.append("Status: ⚠️  CAUTION ADVISED")
        results.append(f"Interactions Found: {len(interactions)}")
        results.append("Recommendation: Consult healthcare provider before proceeding.")
    else:
        results.append("Status: ✓ NO MAJOR CONCERNS")
        results.append("Recommendation: Prescription appears safe based on available data.")

    results.append("")
    results.append("⚕️  DISCLAIMER: This is an AI-assisted analysis tool.")
    results.append("Always consult a licensed healthcare provider for medical decisions.")
    results.append("=" * 60)

    return "\n".join(results)

# ==================== GRADIO INTERFACE ====================

def create_interface():
    with gr.Blocks(theme=gr.themes.Soft(), title="AI Medical Prescription Verifier") as app:
        gr.Markdown("""
        # 🏥 AI Medical Prescription Verification System
        ### Powered by IBM Granite 3.0 2B Instruct Model

        This system provides:
        - 🔍 Drug Interaction Detection
        - 👥 Age-Specific Dosage Recommendations
        - 💊 Alternative Medication Suggestions
        - 🤖 NLP-Based Drug Information Extraction (IBM Granite 2B)
        """)

        with gr.Row():
            with gr.Column():
                prescription_input = gr.Textbox(
                    label="📝 Prescription Text",
                    placeholder="Enter prescription: e.g., 'Take Warfarin 5mg once daily for blood clotting prevention'",
                    lines=5
                )

                age_input = gr.Slider(
                    minimum=1,
                    maximum=120,
                    value=35,
                    step=1,
                    label="👤 Patient Age"
                )

                additional_drugs_input = gr.Textbox(
                    label="💊 Additional Current Medications (Optional)",
                    placeholder="e.g., 'aspirin, metoprolol'",
                    lines=2
                )

                analyze_btn = gr.Button("🔍 Analyze Prescription", variant="primary", size="lg")

            with gr.Column():
                output = gr.Textbox(
                    label="📊 Analysis Report",
                    lines=25,
                    show_copy_button=True
                )

        gr.Markdown("""
        ### 💡 Example Prescriptions to Try:
        - **High Risk**: "Warfarin 5mg daily and Aspirin 100mg daily for heart health"
        - **Pediatric**: "Amoxicillin 250mg three times daily for infection" (Age: 8)
        - **Geriatric**: "Metoprolol 100mg twice daily and Lisinopril 20mg daily" (Age: 75)
        - **Complex**: "Ciprofloxacin 500mg twice daily, currently on Warfarin and Theophylline"
        """)

        analyze_btn.click(
            fn=analyze_prescription,
            inputs=[prescription_input, age_input, additional_drugs_input],
            outputs=output
        )

        gr.Markdown("""
        ---
        ⚕️ **Medical Disclaimer**: This tool is for educational purposes only.
        Always consult qualified healthcare professionals for medical advice.
        """)

    return app

# ==================== LAUNCH APPLICATION ====================

if __name__ == "__main__":
    print("\n" + "="*60)
    print("🏥 AI Medical Prescription Verification System")
    print("="*60)
    print(f"✓ Model: {model_name}")
    print(f"✓ Drugs in database: {len(DRUG_DATABASE)}")
    print(f"✓ Device: {model.device}")
    print("="*60 + "\n")

    app = create_interface()
    app.launch(
        share=True,
        debug=True,
        show_error=True
    )



